hostname1:
  - type: ssh
    ip: 192.168.1.10
    port: 22
    username: admin
    password: cisco123
  - type: telnet
    ip: 192.168.1.10
    port: 23
    username: admin
    password: cisco123
  - type: console_ssh
    ip: 192.168.1.20
    port: 2222
    username: console
    password: c0ns0le
  - type: console_telnet
    ip: 192.168.1.20
    port: 2323
    username: console
    password: c0ns0le
